### ISSUE TITLE
simple_formatでaタグのtarget属性を除去しないで表示したい

### ISSUE THREAD

**Issue by hak-chami** [hak-chami/chobi_memo#14]
# やりたいこと

**simple_formatを利用したままaタグのtarget属性を除去しないで表示したい**

# 試したこと

以下のコードでやりたいこと（simple_formatのデフォルトのsanitizeをを保持したままtarget属性を付与）ができた

```
<%= simple_format(sanitize(@word.content_replace, attributes: %w(href target)), {}, sanitize: false) %>
```
## 上記コードでできたこと

- simple_formatで許可されていないタグ（scriptなど）がきちんと除去される
    - 許可されているタグ（liやbなど）は反映される
- 本来除去対象のtarget属は除去されず、リンクを別窓で開ける

# わからないこと

**なぜこのコードでsimple_formatのデフォルトのsanitizeを保持したままtarget属性を付与できるのか**

## 理解していること

- sanitize
    - 与えられた文字列から要素と属性を除去する
    - 引数がない場合デフォルトで決められた要素と属性を除去する
    - 引数がある場合は指定した要素と属性以外全て除去する
        - @word.content_replaceからhrefとtarget以外の要素と属性が除去される
- simple_format
    - simple_format内でtextをsanitizeしている
    - オプションで`sanitize: false`を指定するとsanitizeしない

### 上記理解していることを踏まえて考えられたこと

- simple_formatのオプションで`sanitize: false`を指定しているが、その前に@word.content_replaceをsanitizeすることで@word.content_replaceの内容からデフォルトで決められた要素と属性を除去されたのかと思った。
- しかし、sanitizeで引数を指定していることによりhrefとtarget以外の要素と属性が除去されたと理解できる。
- にも関わらず表示された@word.content_replaceはきちんとデフォルトのsanitizeが適用されているようだった。

**Comment by ArakawaShintaro** [comment]
ぱっと見、
`simple_format(@word.content_replace, {}, sanitize: false)` じゃだめなのかな？ともおもいましたがどうでしょう

**Comment by ArakawaShintaro** [comment]
# 結論
sanitize(hoge, attributes: %w(href target))でtarget属性とhref属性を許可し、
かつ、simpe_formatでsanitize: falseしているので、target属性は残ったままになる

# その他レビュー
- simple_format(@word.content_replace, {}, sanitize: false) で十分そう
  - ただ`@word.content_replace`がどういった値か不明のため、いけそうとしか言えないです
- 参照しているかもしれませんが、公式のドキュメントは必ずみましょう
  - http://api.rubyonrails.org/

**Comment by hak-chami** [comment]
@word.content_replaceはユーザー自身が登録したい単語のメモを入力する場所です。
フォームの内容自体は@word.contentで受け取りますが、そこに記述された特定の書き方で書かれた文字列をaタグで置き換えリンクとして表示できるようになっています。
この時、HTMLに置き換えたメモの内容を保存する場所を@word.content_replaceとしています。

**Comment by hak-chami** [comment]
`simple_format(@word.content_replace, {}, sanitize: false)`

確かに今回はこれでもやりたいことはやれると思いました。
しかし、上記の書き方だとscriptタグなどが埋め込まれた場合作動してしまうので、今後もし投稿を不特定多数と共有するようになる場面を考えた場合、あらかじめ許可してあるもの以外の不要なタグは動作させない方が良いのでは無いかと考えました。

**Comment by hak-chami** [comment]
# sanitizeメソッドについて

上記理解していること、でも書きましたがこのメソッドについては

- 引数がある場合は指定した要素と属性以外全て除去する

ものだと認識していました。

ただ、回答を受けてsanitize単体で動かしてみたところ、デフォルトのsanitizeメソッドで許可されているタグに加えてhrefとtargetが許可されているという挙動になりました。

sanitizeがこういう挙動になる以上、

```
<%= simple_format(sanitize(@word.content_replace, attributes: %w(href target)), {}, sanitize: false) %>
```
で意図した処理が得られるのは納得がいくところです。

## 結論として

sanitizeメソッドでは**引数を与えるとデフォルトのホワイトリストに加えて要素や属性を許可できる**、ということなのでしょうか？

**Comment by ArakawaShintaro** [comment]
> sanitizeメソッドでは引数を与えるとデフォルトのホワイトリストに加えて要素や属性を許可できる、ということなのでしょうか？

```ruby
# Providing custom whitelisted tags and attributes:

<%= sanitize @comment.body, tags: %w(strong em a), attributes: %w(href) %>
```
公式にはそのように書かれていると思います。

**Comment by hak-chami** [comment]
カスタムホワイトリストがどういう意味なのかイマイチよく分からない感じでしたが、その後自分でも色々検証した結果今回のコードについては、**タグの指定はせず属性の指定だけしたことから、タグにはデフォルトのホワイトリストが、属性にはカスタムホワイトリストが適用されていた**ということがわかりました。

これで解決した感じがします。
ありがとうございました！
