### ISSUE TITLE
TODOリスト（期日見積もりの練習）

### ISSUE THREAD

**Issue by ArakawaShintaro** [hak-chami/chobi_memo#19]
# TODO
- フロント
  - Bootstrapでデザイン
    - リンクの色
    - 全体のカラーを統一する
  - LP
  - サイトのキャラクター
    - キャラクター作成
    - キャラクターをサイトに反映

- サーバーサイド
  - （仮）インクリメンタルサーチ
    - 時間がかかりそうなら、普通の検索

- herokuを使用してアップロード

**Comment by hak-chami** [comment]
- フロント

    - Bootstrapでデザイン
        - リンクの色：7/21
        - 全体のカラーを統一する：7/22
    - LP
    - サイトのキャラクター
        - キャラクター作成：7/23
        - キャラクターをサイトに反映：7/25
- サーバーサイド

    - （仮）インクリメンタルサーチ
        - 時間がかかりそうなら、普通の検索：7/31
- herokuを使用してアップロード：8/5

**Comment by ArakawaShintaro** [comment]
一旦全て終わったのでcloseして大丈夫です。
本に着手していきましょう。
