### ISSUE TITLE
Herokuについて

### ISSUE THREAD

**Issue by hak-chami** [hak-chami/chobi_memo#23]
# Herokuとは

- PaaS（Platform as a Service）と呼ばれるサービスで、アプリケーションを実行するためのプラットフォーム（サーバやOS、データベースなどのこと）
    - PaaS＝WEBアプリケーションの公開に関わる環境構築や作業を代行してくれるサービス

## 利用できる言語

- Node.js
- Ruby
- Python
- Java
- PHP
- Go
- Scala
- Clojure
- Kotlin

https://devcenter.heroku.com/categories/language-support

## 特徴

- SSLやメール配信などの、WEBアプリケーションで頻繁に利用される機能がアドオン（拡張機能）として提供されている
- 他のクラウド環境などと異なり、最初から設計しておかなくてもスケールアウトが簡単に行える
- herokuが提供する機能には、開発に利用する機能の他にも、ログの確認やパフォーマンスのモニタリング、データベースのバックアップといった運用をサポートする機能も含まれている

## Herokuのフリープランについて

- フリープランでは30分間アクセスがない場合スリープしてしまう
- また、1日6時間以上はスリープさせる必要がある（スリープ状態でも再びアクセスすればRailsは起動する）
- 常時起動が必要な場合は有料プランを検討すること

# Herokuでのアプリケーション公開方法

Herokuでアプリケーションを作成し、gitでHerokuが用意したgitリポジトリにpushする。

## 本番環境用の設定をする

Railsでは環境ごとにアプリケーションの設定をすることが可能で、Heroku上で動かす時は **本番環境用（production）** の設定が反映される。
※`rails s`でサーバーを起動させた時は **開発用（development）** で起動するようになっている。

| 名前 | 目的 |
----|---- 
| production | 本番環境用 |
| development | 開発用 |
| test | テスト用 |

### DBの変更

Railsデフォルトの設定ではDBにSQLiteを使用しているが、Herokuでは使用できないので使用するDBを変更する必要がある。（推奨はPostgreSQL）

- Gemfileの変更
- データベース設定の変更

**今回のアプリ（ChobiMemo）は開発環境からPostgreSQLを使用しているので変更する必要はない。**

## Heroku CLIのインストール

PCとHerokuを繋ぐためにHeroku CLIを[インストール](https://devcenter.heroku.com/articles/heroku-cli)する。
インストールすることによりターミナルでherokuコマンドが使用できるようになる。

### インストールの確認
下記コマンドを実行してバージョンを確認。
```
$ heroku --version
```

### Herokuへログイン
```
$ heroku login
```
コマンドを実行してアカウント情報を入力、Herokuにログインする。

## Heroku上にアプリケーションを作成する

```
$ heroku create (アプリケーション名)
```
※アプリケーション名はユニークである必要があるので注意

## Herokuへデプロイする

Heroku上にアプリケーションを作成すると"heroku"というgitリモートリポジトリが一つ登録される。
HerokuのgitリポジトリのmasterブランチにpushすることでHeokru上でアプリケーションを動かすことができる。

```
$ git push heroku master
```

## Herokuでマイグレーションを実行

Heroku上でデータベースを初期化する。

```
$ heroku run rake db:migrate
```

## アプリケーションにアクセスする

```
$ heroku open
```

もしくは`http://（Herokuアプリケーション名）.herokuapp.com`でHerokuにデプロイしたアプリケーションへアクセスできる。

---
 
参考文献：

https://devcenter.heroku.com/categories/ruby-support
https://devcenter.heroku.com/articles/getting-started-with-rails5
https://www.sejuku.net/blog/7858
https://tech-camp.in/note/technology/16108/
https://techacademy.jp/magazine/6401
https://qiita.com/NaokiIshimura/items/eee473675d624a17310f

**Comment by ArakawaShintaro** [comment]
参考文献も記載しておきましょう。
